CREATE TABLE workstations (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE cameras (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    workstation_id BIGINT REFERENCES workstations
);